### PR TITLE
Resolves #7 by initializing Remix's Blues Stack

### LINKED ISSUE #7: Setup project using Remix Blues Stack
## Description
We need an initial setup for Starchart using [Remix Blues Stack](https://github.com/remix-run/blues-stack) script as a starting point so that required features and functionalities from [Satellite](https://github.com/Seneca-CDOT/satellite) can be ported over later. 

### Resources
[Remix Blues Stack](https://github.com/remix-run/blues-stack)

### PR DESCRIPTION
**Pull request by SerpentBytes**
## Description
This PR resolves #7 by providing an initial Remix's Blues Stack for the Starchart project. 

### Pre-requisites to Testing
- Install and set up Postgres so the Remix app runs successfully. I used [Postgres App Client](https://postgresapp.com/downloads.html) as it does the job quickly and is easy to use
### Steps to Test
1. Install dependencies using `npm install`
2. Run `npx remix init`
3. Run `npm run docker`
4. Run `npm run setup`
5. Run `npm run build`
6. Run `npm run dev`

Now, navigate to `localhost:3000` to see Remix App up and running:

Screenshot 2023-01-26 at 10 27 52 PM

### Additional Information
- To avoid duplicate files, Remix's Blues Stack's code from `docker-compose.yml` and `.gitingore`, was added to existing Starchart files with the same name
- `README.md` file from Remix's Blues Stack is titled `README-remix.md`, it can be moved to the wiki or somewhere else

### Resource
https://github.com/remix-run/blues-stack

### CODE REVIEW

**Review by humphd — APPROVED** [review]
There's a lot I want to change in this, but it's all stuff we can do in follow-ups so that others can get going.

Thanks for doing this so quickly!  It gets us going fast.

**Comment by Myrfion** [comment]
Hello @SerpentBytes, thank you for your PR. I tried to run it on my machine and `docker-compose.yml` doesn't seem to be valid so I can't run `npm run docker`. Here is what I am getting when trying to run it: 
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
'postgres' does not match any of the regexes: '^x-'
```

**Comment by humphd** [comment]
You can delete all the existing code in the `docker-compose.yml` file and replace it with what you need for this.  We don't need any of it.

**Comment by SerpentBytes** [comment]
I have removed Postgres-related code from `docker-compose.yml`; it should work now.

**Review by humphd — APPROVED** [review]
Like I said before, lots of stuff to fix later on, but this is great to get in so we can start.

**Review by Myrfion — APPROVED** [review]
As @humphd mentioned, a lot of stuff to be fix/remove, but it's better to ship it fast to unblock everybody else

**Pull request merged**
