### PR TITLE
Fix Blue Stack so it runs with dockerized MySQL

### PR DESCRIPTION
**Pull request by humphd**
@Ririio from Slack last night:

> Has anyone successfully managed to run the app? I seem to be getting an error regarding invalid database credentials when I run on either dev or initial setup, build seems to be working fine:
`Error: Authentication failed against database server at `localhost`, the provided database credentials for `postgres` are not valid.
Please make sure to provide valid database credentials for the database server at `localhost`.

This PR gets the `main` branch working again using MySQL in docker.  To use it:

```
# Create an .env based on the example
$ cp .env.example .env

# Start MySQL in docker
$ docker compose up
# Wait for the db to finish starting, it takes a few seconds before it's ready...

# Setup the database
$ npm run setup

# Start the app, which will be running on localhost:3000
$ npm run dev

# You can visually see the database using:
$ npm run db:studio
```

The other changes I've made in this:

- Updated the Prisma schema to be very small (just a User table with a few fields)
- Added .gitignore for a `mysql-data/` directory, where your database files will go.  You can delete this folder to reset the database
- Removed Tailwind so we don't have issues with the build
- Removed the Fly.io/Postgres stuff
- Did some light refactoring of the user session stuff so things will compile.  It needs more work

### CODE REVIEW

**Comment by shawnyu5** [comment]
Running `docker compose up` in this PR, the db does not seem to be able to initialize. This is the logs from docker compose

```
[+] Running 1/0
 ⠿ Container database  Created                                                                                                                                                             0.0s
Attaching to database
database  | 2023-01-28 20:21:20+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
database  | 2023-01-28 20:21:21+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
database  | 2023-01-28 20:21:21+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
database  | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
database  | 2023-01-28T20:21:22.176061Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
database  | 2023-01-28T20:21:22.179572Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
database  | 2023-01-28T20:21:22.241708Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
database  | 2023-01-28T20:21:22.558597Z 1 [ERROR] [MY-012960] [InnoDB] Cannot create redo log files because data files are corrupt or the database was not shut down cleanly after creating the data files.
database  | 2023-01-28T20:21:22.853283Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
database  | 2023-01-28T20:21:22.853683Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
database  | 2023-01-28T20:21:22.854121Z 0 [ERROR] [MY-010119] [Server] Aborting
database  | 2023-01-28T20:21:22.855646Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.32)  MySQL Community Server - GPL.
database exited with code 1
```

**Comment by humphd** [comment]
@shawnyu5 which OS are you running?

The error is:

> Cannot create redo log files because data files are corrupt or the database was not shut down cleanly after creating the data files.

Which means it's not liking the volume we're mounting, or perhaps that the image you're using is corrupt?

I would try to do:

```sh
$ docker compose down
$ rm -fr mysql-data
$ docker compose up
```

Did that work?  If not, try removing the MySQL image and trying, then try deleting the volume and try again.

Let me know what happens.

**Comment by SerpentBytes** [comment]
I just tested the PR. It works on macOS.

**Comment by shawnyu5** [comment]
I'm running this on Linux. Removing `mysql-data/`, and the docker volume that was generated. Then running `docker compose up`. The database was able to initialize properly.

However, following the instructions for starting the app in #38 

> Run `npx remix init`
Run `npm run docker`
Run `npm run setup`
Run `npm run build`
Run `npm run dev`

`npm run build` produces the following error:

```
✘ [ERROR] No matching export in "app/models/user.server.ts" for import "getUserById"

    app/session.server.ts:5:9:
      5 │ import { getUserById } from "~/models/user.server";
        ╵          ~~~~~~~~~~~


Build failed with 1 error:
app/session.server.ts:5:9: ERROR: No matching export in "app/models/user.server.ts" for import "getUserById"
Error
    at Object.onCompileFailure (/home/shawn/starchart/node_modules/@remix-run/dev/dist/cli/commands.js:179:13)
    at Object.compile (/home/shawn/starchart/node_modules/@remix-run/dev/dist/compiler/remixCompiler.js:33:134)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.build (/home/shawn/starchart/node_modules/@remix-run/dev/dist/compiler/build.js:33:3)
    at async Object.build (/home/shawn/starchart/node_modules/@remix-run/dev/dist/cli/commands.js:174:3)
    at async Object.run (/home/shawn/starchart/node_modules/@remix-run/dev/dist/cli/run.js:448:7)
ERROR: "build:remix" exited with 1.
```

And `npm run dev` starts an incomplete web app with these errors:

```
No routes matched location "/build/_assets/tailwind-CAZEXCOM.css" 
ErrorResponse {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/build/_assets/tailwind-CAZEXCOM.css"',
  error: Error: No route matches URL "/build/_assets/tailwind-CAZEXCOM.css"
      at getInternalRouterError (/home/shawn/starchart/build/server.js:38817:59)
      at Object.query (/home/shawn/starchart/build/server.js:38143:23)
      at handleDocumentRequestRR (/home/shawn/starchart/build/server.js:39675:39)
      at requestHandler (/home/shawn/starchart/build/server.js:39591:28)
      at /home/shawn/starchart/build/server.js:40748:32
      at /home/shawn/starchart/build/server.js:40874:12
      at Layer.handle [as handle_request] (/home/shawn/starchart/build/server.js:17998:9)
      at next (/home/shawn/starchart/build/server.js:18167:17)
      at next (/home/shawn/starchart/build/server.js:18163:11)
      at next (/home/shawn/starchart/build/server.js:18163:11)
}
No routes matched location "/build/_assets/tailwind-CAZEXCOM.css" 
ErrorResponse {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/build/_assets/tailwind-CAZEXCOM.css"',
  error: Error: No route matches URL "/build/_assets/tailwind-CAZEXCOM.css"
      at getInternalRouterError (/home/shawn/starchart/build/server.js:38817:59)
      at Object.query (/home/shawn/starchart/build/server.js:38143:23)
      at handleDocumentRequestRR (/home/shawn/starchart/build/server.js:39675:39)
      at requestHandler (/home/shawn/starchart/build/server.js:39591:28)
      at /home/shawn/starchart/build/server.js:40748:32
      at /home/shawn/starchart/build/server.js:40874:12
      at Layer.handle [as handle_request] (/home/shawn/starchart/build/server.js:17998:9)
      at next (/home/shawn/starchart/build/server.js:18167:17)
      at next (/home/shawn/starchart/build/server.js:18163:11)
      at next (/home/shawn/starchart/build/server.js:18163:11)
}
...
```
The app is available to visit on localhost:3000. But some css seems to be missing, so it looks all out of proportion.

**Comment by shawnyu5** [comment]
Can you get the app to run @SerpentBytes?

**Comment by SerpentBytes** [comment]
> Can you get the app to run @SerpentBytes?

After running `npm run setup`, I opened a new tab in the terminal and ran `npm run dev`, and it works.

**Comment by humphd** [comment]
@shawnyu5 sounds like we can close this then.

The errors you mention on startup are all related to bits of Blue Stack we need to rip out and fix.  This PR is just about getting the db to work.

**Comment by humphd** [comment]
It's the TS build that's failing, since the code is clearly broken atm, where as `dev` likely works without a full build.

**Comment by sirinoks** [comment]
> The errors you mention on startup are all related to bits of Blue Stack we need to rip out and fix. This PR is just about getting the db to work.

Created an [issue](https://github.com/Seneca-CDOT/starchart/issues/52) about this

**Comment by humphd** [comment]
Need some reviews to get this in.

**Comment by shawnyu5** [comment]
Could you add me as a contributor

**Comment by humphd** [comment]
@shawnyu5 done

**Review by SerpentBytes — APPROVED** [review]

**Review by shawnyu5 — APPROVED** [review]

**Comment by humphd** [comment]
We should get another issue that starts to document how to setup the dev environment, and this will be a start:

```sh
# Create an .env based on the example
$ cp .env.example .env

# Start MySQL in docker
$ docker compose up
# Wait for the db to finish starting, it takes a few seconds before it's ready...

# Setup the database
$ npm run setup

# Start the app, which will be running on localhost:3000
$ npm run dev

# You can visually see the database using:
$ npm run db:studio
```

Someone want to file/fix that?  It could go in `CONTRIBUTING.md` or a Contributing wiki page (might be better).

**Comment by sirinoks** [comment]
> We should get another issue that starts to document how to setup the dev environment
> Someone want to file/fix that? It could go in CONTRIBUTING.md or a Contributing wiki page (might be better)

@humphd Wait. Do you mean we need another issue, besides the ones we already have? We got  #12 and #29 - are those different things?

**Comment by humphd** [comment]
no, just that my notes could get added to an issue (i.e., so they don't get lost)

**Comment by sirinoks** [comment]
I'll add that to [this wiki page](https://github.com/Seneca-CDOT/starchart/wiki/%5BUnder-construction%5D-Set-up-documentation) then

**Pull request merged**
